version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be_elearning_app
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - storage_data:/var/www/html/storage
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.2
    container_name: be_elearning_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./e_learning.sql:/docker-entrypoint-initdb.d/e_learning.sql:ro
    environment:
      MYSQL_DATABASE: e_learning_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: root_pass

volumes:
  db_data:
  vendor_data:
  storage_data:
