export const CREDENTIALS = {
    AUTHENTICATION_TOKEN: 'AUTHENTICATION_TOKEN',
    IS_LOGIN: 'IS_LOGIN',
    USER_INFO: 'USER_INFO',
}

export const CART = {
    COUNT: 'CART_COUNT',
}

export const NOTIFICATION = {
    COUNT: 'NOTIFICATION_COUNT',
}

export const HAS_REQUESTED_INSTRUCTOR = 'HAS_REQUESTED_INSTRUCTOR'
export const SHOW_VERIFICATION_REMINDER = 'SHOW_VERIFICATION_REMINDER'
